### ISSUE TITLE
Modify embedded scripts in the chaincode branch so that they now call the router.sh scripts with their respective stages.  

### ISSUE THREAD

**Issue by jorgedr94** [IBM-Blockchain-Starter-Kit/blockchain-toolchain#20]

**Comment by yorhodes** [comment]
We have to create two separate buttons for composer/chaincode in the README and provide ```$platform=<platform>``` arguments in the query. This variable should be used as the platform argument for the router call from the embedded scripts in the pipeline.yaml.

**Comment by jorgedr94** [comment]
@mayarobin  I think that this issue can now be closed.
