### ISSUE TITLE
How to change toolchain for more than 2 organisations?

### ISSUE THREAD

**Issue by simonmullaney** [IBM-Blockchain-Starter-Kit/blockchain-toolchain#36]
Just wondering if anyone knows how this can be done - I want the toolchain to deploy 6 organisations instead of two?

Any help is greatly appreciated!

**Comment by jt-nti** [comment]
Hi @simonmullaney, there's a [config file](https://github.com/IBM-Blockchain-Starter-Kit/chaincode-bootstrap/blob/master/deploy_config.json) in the chaincode bootstrap project which I think should do what you want when you use the [chaincode toolchain](https://github.com/IBM-Blockchain-Starter-Kit/blockchain-toolchain/tree/chaincode).

There's another issue, IBM-Blockchain-Starter-Kit/build-lib#34, to work out whether there's a better way to handle that sort of configuration which I'd be interested to know your thoughts on. I'll close this issue but please let me know how you get on via [Gitter](https://gitter.im/IBM-Blockchain-Starter-Kit/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)
